### PR TITLE
JMH Benchmarking details

### PR DESCRIPTION
**Pull request by mohanr**
I am creating a request so that my addition can be reviewed. My draft contains code, benchmark results and some graphs plotted using 'R'. More explanations can be added if the draft is reviewed and considered  appropriate. The actual code used to plot 'R' graphs using the 'dplyr' package is in my blog http://branetheory.org/2015/06/18/parsing-java-micro-benchmarking-harness-data-using-dplyr-part-2/

### CODE REVIEW

**Comment by neomatrix369** [comment]
@mohanr  - Your branch is not in sync with master, can't merge this pull request.

Also did you collaborate with @mitemitreski over this topic, please do if you haven't, as he has vested interested in this area.

**Comment by neomatrix369** [comment]
General comment: just a query, are there sufficient explanations under the pictures and the code that has been submitted along with this work ?

**Comment by mohanr** [comment]
Not enough explanations have been added yet.If this format is acceptable I
can add more explanations.

I sent a mail to @mitemitreski(copied in this mail also) earlier.
Based on my little knowledge of Git I think I have to fork freshly again.

Thanks.

**Comment by znurgl** [comment]
Just follow this description (via GitHub): http://neomatrix369.gitbooks.io/adoptopenjdk-getting-started-kit/content/en/contribute.html

**Comment by mohanr** [comment]
I did that for my first pull request. The fork is stale now. I think I may
have to 'rebase' it.

Mohan

**Comment by neomatrix369** [comment]
create a new branch,
cherry pick from old branch,
zap the old branch,
rename the old to new branch (name).
and force push into your old branch which now will have all commits synced
with master.

Cheers,

**Comment by mohanr** [comment]
I do see a synched view in GitX with this. Hope it is fine ? I will add
more explantions in the next step.

git checkout -b jmhbranch origin

git rebase master jmhbranch

git status

           On branch jmhbranch

           Your branch is up-to-date with 'origin/master'.

            nothing to commit, working directory clean

git branch -d jmhbranch

            Deleted branch jmhbranch (was f2d94b0).

git branch -m jmhbranch

git push origin jmhbranch --force

Thanks.

**Comment by neomatrix369** [comment]
I think yoi can do a 

```
git checkout master
git pull
git checkout jmhbranch
```
```
git merge master
```
or
```
git pull --rebase origin master
```

**Comment by mohanr** [comment]
Mani,

    Are you suggesting that I do this too ?

Mohan

**Comment by neomatrix369** [comment]
Whatever you have done, hasn't work for one reason or other, github has provided some hints see below:

Checkout via command line
If you cannot merge a pull request automatically here, you have the option of checking it out via command line to resolve conflicts and perform a manual merge.
 HTTPS
 Git
Patch
	
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b mohanr-master master
git pull https://github.com/mohanr/adoptopenjdk-getting-started-kit.git master
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff mohanr-master
git push origin master

You get this same instructions when you click on the ```Use the command line to resolve conflicts before continuing.```

**Comment by mohanr** [comment]
I did this now.

Thanks,
Mohan

**Comment by neomatrix369** [comment]
It didn't the conflicts between your branch that you had forked long ago and our repo, I manually cloned it on my end and fixed it for you. Can you please check if your changes are intact - I think they are.

Also please remove (delete) your local and remote repo's and reclone them - best way to fix it for you, since you are new to git. Before that please make copies of any changes you have made onto a separate folder.

**Comment by mohanr** [comment]
Sure. I should research GIT so that I don't cause trouble here. I have to
add some more clear details too.  More than one set of measurements could
reduce the standard error in the graphs. CI should also be clearly marked
in the Graph.


Thanks.

**Comment by neomatrix369** [comment]
@mohanr - git will play a big role with amending this book, so please take time to look into it. We all have been through this before so its not a worry. 

As for the format, it would be great if you split each section into a sub-page under the JMH node and moved the content to that page, just now its a lot of scrolling to learn about the content is going on.

Also narratives of what you understand the different graphs and metrics mean will also help those who looking at it - and will also help receive feedback from others.

Thanks in advance.

**Comment by mohanr** [comment]
I will surely work on that.

Thanks.

**Pull request merged**
