### PR TITLE
Build your own VM in the Cloud with AWS

### PR DESCRIPTION
**Pull request by AlimacsMusings**
Added "Build your own VM in the Cloud with AWS" to virtual_machines.md with a link to a blog detailing how to set up and use an Amazon Web Services EC2 VM.  For use on LJC Hackdays.

### CODE REVIEW

**Comment by neomatrix369** [comment]
Nice work @AlimacsMusings  - can you also mention this link on https://neomatrix369.gitbooks.io/adoptopenjdk-getting-started-kit/content/en/binaries/build_your_own_openjdk.html, there is text on the cloud, if you make that into a hyperlink and make it point to your blog, that would be awesome.

**Comment by AlimacsMusings** [comment]
HI @neomatrix369.  I've made the change and pushed this.

**Comment by neomatrix369** [comment]
Looks nice, just a minor suggestion, could you make the whole text "build it on the cloud environment" a hyperlink. I'll merge right after.

**Comment by AlimacsMusings** [comment]
Done.  Apologies, I misunderstood.  I have left "cloud" in bold.

**Comment by neomatrix369** [comment]
All good!

**Pull request merged**
